services:
  _defaults:
    autowire: true
    autoconfigure: false

  Zan\DoctrineRestBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  Zan\DoctrineRestBundle\EntitySerializer\MinimalEntitySerializer: ~

  Zan\DoctrineRestBundle\Permissions\PermissionsCalculatorFactory: ~

  Zan\DoctrineRestBundle\EntityMiddleware\EntityMiddlewareRegistry:
    arguments:
      - !tagged_iterator zan.drest.entity_middleware
      - '@annotation_reader'

  #
  # Public services
  Zan\DoctrineRestBundle\EntityResultSet\EntityResultSetFactory:
    public: true