services:
  _defaults:
    autowire: true
    autoconfigure: false

  Zan\DoctrineRestBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  Zan\DoctrineRestBundle\Loader\ApiEntityLoader:
    public: true

  Zan\DoctrineRestBundle\ExcelImport\ExcelTemplateImporter:
    public: true

  Zan\DoctrineRestBundle\EntitySerializer\MinimalEntitySerializer:
    public: true

  Zan\DoctrineRestBundle\Permissions\PermissionsCalculatorRegistry:
    public: true
    arguments:
      - !tagged_iterator zan.permissions_calculator

  Zan\DoctrineRestBundle\Permissions\PermissionsCalculatorFactory:
    public: true

  Zan\DoctrineRestBundle\EntityMiddleware\EntityMiddlewareRegistry:
    public: true
    arguments:
      - !tagged_iterator zan.drest.entity_middleware
      - '@annotation_reader'

  Zan\DoctrineRestBundle\Listener\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  Zan\DoctrineRestBundle\EntityResultSet\EntityResultSetFactory:
    public: true