services:
  _defaults:
    autowire: true
    autoconfigure: false

  Zan\DoctrineRestBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  Zan\DoctrineRestBundle\EntitySerializer\MinimalEntitySerializer: ~

  Zan\DoctrineRestBundle\Permissions\PermissionsCalculatorFactory: ~

  Zan\DoctrineRestBundle\EntityMiddleware\EntityMiddlewareRegistry:
    arguments:
      - !tagged_iterator zan.drest.entity_middleware
      - '@annotation_reader'

  Zan\DoctrineRestBundle\Listener\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  #
  # Public services
  Zan\DoctrineRestBundle\EntityResultSet\EntityResultSetFactory:
    public: true